title: Visual Analysis of FIFA 19 Data
description: Data Science Project with Python to analyze and discover insights of the detailed attributes of each player registered in the latest edition of FIFA 19 database
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
